/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingwarnet_Operator;

import javax.swing.JOptionPane;

/**
 *
 * @author Hafiz
 */
public class editProfile extends javax.swing.JPanel {

    /**
     * Creates new form editProfile
     */
    public editProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEditProfile = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgEditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/editPofil.png"))); // NOI18N
        add(bgEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 650));

        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        JOptionPane.showMessageDialog(this, "Berhasil Disimpan !!");
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgEditProfile;
    private javax.swing.JButton btnSimpan;
    // End of variables declaration//GEN-END:variables
}
