/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingwarnet_Operator;

import java.awt.GridBagLayout;

/**
 *
 * @author Hafiz
 */
public class halamanUtama extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    komputer p1;
    harga p2;
    log p3;
    editProfile p5;
    jadwalShifting p6;
    memo p7;
    
    public halamanUtama() {
        initComponents();
        p1 = new komputer();
        p2 = new harga();
        p3 = new log();
        p5 = new editProfile();
        p6 = new jadwalShifting();
        p7 = new memo();
        jPanel1.setLayout(layout);
        jPanel1.add(p1);
        jPanel1.add(p2);
        jPanel1.add(p3);
        jPanel1.add(p5);
        jPanel1.add(p6);
        jPanel1.add(p7);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgHome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        harga = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        btnJadwalShifting = new javax.swing.JButton();
        btnMemo = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/home.png"))); // NOI18N
        getContentPane().add(bgHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 1090, 650));

        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 220, 70));

        harga.setText("jButton1");
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 160, 60));

        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        getContentPane().add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 130, 50));

        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, 60));

        btnJadwalShifting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalShiftingActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalShifting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, 50));

        btnMemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 250, 60));

        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 250, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
         p1.setVisible(true);
         p2.setVisible(false);
         p3.setVisible(false);
         p5.setVisible(false);
         p6.setVisible(false);
         p7.setVisible(false);
        
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
          p1.setVisible(false);
          p2.setVisible(true);
          p3.setVisible(false);
          p5.setVisible(false);
          p6.setVisible(false);
          p7.setVisible(false);
          
        
        
    }//GEN-LAST:event_hargaActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
          p1.setVisible(false);
          p2.setVisible(false);
          p3.setVisible(true);
          p5.setVisible(false);
          p6.setVisible(false);
          p7.setVisible(false);
        
        
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
          p1.setVisible(false);
          p2.setVisible(false);
          p3.setVisible(false);
          p5.setVisible(true);
          p6.setVisible(false);
          p7.setVisible(false);
        
        
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnJadwalShiftingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalShiftingActionPerformed
          p1.setVisible(false);
          p2.setVisible(false);
          p3.setVisible(false);
          p5.setVisible(false);
          p6.setVisible(true);
          p7.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnJadwalShiftingActionPerformed

    private void btnMemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoActionPerformed
          p1.setVisible(false);
          p2.setVisible(false);
          p3.setVisible(false);
          p5.setVisible(false);
          p6.setVisible(false);
          p7.setVisible(true);
          
    }//GEN-LAST:event_btnMemoActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         new login ().setVisible(true);
         this.dispose();
        
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgHome;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwalShifting;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMemo;
    private javax.swing.JButton harga;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
