/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingwarnet_Operator;

/**
 *
 * @author Hafiz
 */
public class jadwalShifting extends javax.swing.JPanel {

    /**
     * Creates new form jadwalShifting
     */
    public jadwalShifting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJadwalShifting = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgJadwalShifting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/jadwalShifting.png"))); // NOI18N
        add(bgJadwalShifting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 650));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgJadwalShifting;
    // End of variables declaration//GEN-END:variables
}
